### ISSUE TITLE
back and forth scan angles are off by one step

### ISSUE THREAD

**Issue by decarlof** [tomography/tomoscan#160] opened 2022-11-02 15:10 UTC
When doing back and forth scans, the angles of the back scan are off by one angular step.
[window_start, window_end, range_length](https://github.com/decarlof/tomoscan/blob/4d94c10a17940308644014f05b4e44b37e5f8a7f/tomoscan/tomoscan_pso.py#L242)  and [taxi_dist](https://github.com/decarlof/tomoscan/blob/4d94c10a17940308644014f05b4e44b37e5f8a7f/tomoscan/tomoscan_pso.py#L314) are set correctly in both back and forth scans, so we do not understand why the back direction is assigning the first angular position off by one angular step. We temporarily fix it with [this](https://github.com/decarlof/tomoscan/blob/4d94c10a17940308644014f05b4e44b37e5f8a7f/tomoscan/tomoscan_pso.py#L329) but it will be good to understand if this is happening at the rotary stage driver level (ensemble) and if it is not an issue for other drivers (A3200)?

**Comment by decarlof** [comment] 2022-11-03 14:44
to test you can run 2 scans:

- rot_start = 0, rot_step = 0.12, num_angles = 1501
- rot_start = 180, -0.12, num_angles = 1501

the reconstructions I get are off by the rot_step size but I am not sure why this is happening

**Comment by MarkRivers** [comment] 2022-11-03 16:08
Why are you using 1501 angles rather than 1500?

When you reconstruct are you using 1501 angles or 1500?  

If 1500 what angle are your throwing away in each direction?

**Comment by decarlof** [comment] 2022-11-05 21:50
Including the 0 and 180 position is used for rotation axis finding.
I see your point about which angle is thrown away, it is the last (180 in the [0-180] and 0 in the [180-0]), but in both directions each image has the correct angle associated to it. I mean the images taken at 179.88 in the back and forth directions are identical => I would expect identical reconstructions in both directions

**Comment by decarlof** [comment] 2023-01-30 19:27
addressed by https://github.com/tomography/tomoscan/pull/159

**Comment by decarlof** [comment] 2023-04-05 17:43
![Stack](https://user-images.githubusercontent.com/5884150/230159637-2e7cf696-df02-4ee8-bd03-355952fb18eb.gif)


Unfortunately this issue is not solved. Recently taken back-forth scan on the TXM at 32-ID resulted on a reconstruction that is off by 0.8x the step size (see below). This is the very same offset measured also at 2-BM.

Both 2-BM and the TXM at 32-ID use an Aerotech ENSEMBLEML10-40-IO-MXH with 720,000 and 755,200 PSO encoder pulse per rotation.

@MarkRivers @aps-7bm if you can please collect a data set (0-180) and (180-0) on the same sample, so we can determine is a controller or a tomoscan issue.

**Comment by aps-7bm** [comment] 2023-04-05 17:58
I can't take a dataset (I'm set up for HS imaging now), but I may be able
to offer some insight.  I noticed something related when I was working on
the PSO code originally.  If you take tiny steps after the PSO has been
programmed and move back and forth over a region where a PSO pulse should
happen, it doesn't happen at the same spot forward vs. backward.  I never
pursued it because I never do back-and-forth scans.  My suspicion is that
you are seeing the same issue.  We can test this offline either now at 2-BM
or 32-ID or after the dark period starts with a scope.  If this is true, it
may be worth a chat with Aerotech technical support to figure out why.  If
we know the offset and it is (in some way) expected behavior, we can
account for it in the code.

**Comment by MarkRivers** [comment] 2023-04-05 19:51
I can probably find time to do that before the beam goes away.  I have actually never tried back and forth scans.

What am I seeing in the animation window above?

What is the sample size and composition, and how do I get it?

**Comment by MarkRivers** [comment] 2023-04-05 19:54
>if you can please collect a data set (0-180) and (180-0) on the same sample, so we can determine is a controller or a tomoscan issue.

Maybe I misunderstood.  Do you mean the "same sample" you measured, or just that I should to (0-180) and (180-0) on some sample of mine without moving it in between measurements?

**Comment by decarlof** [comment] 2023-04-06 04:51
what you see in the animation are 2 reconstructed slice, one obtained by collecting data (0-180) the second (180-0). They should be identical.

The sample is this case is our alignment pin, I think pixel size was 0.9µm.

If you can do 2 measurements on one of your samples one in the (0-180) and the other in the backwards direction (180-0) that will be very useful to confirm if you see the same or not.

**Comment by decarlof** [comment] 2023-04-06 04:55
Earlier today @timmmooney stated that:

"Going forward and triggering at, say, 27 degrees will take an exposure over a different angular region than going backward and triggering at 27 degrees. I think one copy of the EPICS-database implementation took care to trigger at the beginning of camera intervals on forward scans, and at the end of camera intervals on backward scans."

This may explain the behaviour

**Comment by nikitinvv** [comment] 2023-04-06 13:01
@MarkRivers, to be even more specific, could you please try to run 2 scans of the same sample with the following parameters:
1) start angle = 0, angular step = 1, number of angles=181
2) start angle = 180, angular step = -1, number of angles=181
exposure time doesn't matter, sample sizes/objective also don't matter. 

As a sample you can take a regular needle and put it closer to a border of the field of view. This way the angular difference in reconstructions is more visible.

before running scans, please remove this [line](https://github.com/tomography/tomoscan/blob/4a954d25874849bd00a4b2e622c05ab571600259/tomoscan/tomoscan_pso.py#L330) from your tomoscan code. I added it some time ago because I thought that the error is exactly one step, but in reality it is ~0.8*step (I manually adjusted angles in hdf5 files and checked reconstructions to find it). 

After scanning you can do reconstruction and compare reconstructed slices with the same ids. The animation above is a stack of 2 slices from 2 reconstructed datasets. We expect them to be identical since angles are the same.

**Comment by decarlof** [comment] 2023-04-06 18:31
Here is an explanation from @timmmooney on what is happening (red/green length = exposure times) :


<img width="813" alt="Screenshot 2023-04-06 at 1 27 14 PM" src="https://user-images.githubusercontent.com/5884150/230464641-b3de0e94-610e-4b64-9eb4-275aa0134f56.png">

I think in our case the exposure time and the frame rate are always set so that the exposure time+readout fills completely the time between trigger. I think the  ~ 0.8 * the step size is because we add a margin to the readout. So we are in this situation:

<img width="519" alt="Screenshot 2023-04-06 at 1 34 13 PM" src="https://user-images.githubusercontent.com/5884150/230465569-23ad7fd5-44be-4248-a280-f23989f638c9.png">

so the solution is to re-program the PSO when moving backwards so that the trigger location for backward scans is the forward-scan trigger location plus the angular distance the stage moves during the exposure time.

**Comment by decarlof** [comment] 2023-04-07 02:40
[This commit](https://github.com/tomography/tomoscan/pull/162/commits/a3c46fa8a3ac39f4207a21514824dd1099889748) fixes  issue. We tested it extensively at 2-BM. It should work at other beamlines, you can test it, before merging #162 by installing temporarily [my fork](https://github.com/decarlof/tomoscan.git)

**Closed as completed** 2023-11-29 00:31 UTC
Labels: bug
