### ISSUE TITLE
Convert :download: to :doc: for database documents

### ISSUE THREAD

**Issue by MarkRivers** [tomography/tomoscan#41] opened 2020-05-04 21:39 UTC
The current documentation has :download: for files like tomoScan.template.  This is not convenient for quickly viewing the file.  It gets downloaded and then needs to be opened with an appropriate application.

It is more convenient to use the :doc: link to a .rst document that does a .literalinclude.  The user can then quickly example the file.

This does require an extra .rst file for each document, and a dummy .toctree that includes these files to avoid warnings from Sphinx that the files are not in any toctree.

**Comment by decarlof** [comment] 2020-05-04 22:16
@MarkRivers 's solution better. Now is 2 clicks (one to confirm the download one to open plus the first time to set the editor)

**Comment by decarlof** [comment] 2020-05-05 19:02
@MarkRivers After looking into adding 2-BM templates in the docs, I realized the drop down menu [example_application](https://tomoscan.readthedocs.io/en/latest/source/example_application.html) can became very busy especially if we consider adding docs for multiple beamlines. So I will run in my fork a couple of different layout so we can see how it looks and decide which one to keep.

**Comment by decarlof** [comment] 2020-05-05 19:10
@MarkRivers here is a possible layout for [example_application](https://mytomoscan.readthedocs.io/en/latest/source/example_application.html).

**Comment by MarkRivers** [comment] 2020-05-06 14:20
I pushed a new branch that adds one level of hierarchy:

Base class files
Beamline-specific files

![image](https://user-images.githubusercontent.com/6115534/81187994-64e91380-8f7a-11ea-8204-967e221b9c2a.png)

I also renamed example_application.rst to tomoScanApp.rst for clarity.

I think this makes it nicer.

For some reason my toctree :hidden: no longer seems to be working, so I comment it out.  You will see a bunch of warnings like this:
```
/home/epics/support/tomoscan/docs/source/tomoScan.substitutions.rst: WARNING: document isn't included in any toctree
/home/epics/support/tomoscan/docs/source/tomoScan.template.rst: WARNING: document isn't included in any toctree
/home/epics/support/tomoscan/docs/source/tomoScan_13BM.template.rst: WARNING: document isn't included in any toctree
/home/epics/support/tomoscan/docs/source/tomoScan_13BM_settings.req.rst: WARNING: document isn't included in any toctree
/home/epics/support/tomoscan/docs/source/tomoScan_settings.req.rst: WARNING: document isn't included in any toctree
```
Maybe you can figure out why the hidden attribute is no longer working?

**Comment by MarkRivers** [comment] 2020-05-06 15:31
![image](https://user-images.githubusercontent.com/6115534/81187994-64e91380-8f7a-11ea-8204-967e221b9c2a.png)

I also renamed example_application.rst to tomoScanApp.rst for clarity.

I think this makes it nicer.

For some reason my toctree :hidden: no longer seems to be working, so I comment it out.  You will see a bunch of warnings like this:
```
/home/epics/support/tomoscan/docs/source/tomoScan.substitutions.rst: WARNING: document isn't included in any toctree
/home/epics/support/tomoscan/docs/source/tomoScan.template.rst: WARNING: document isn't included in any toctree
/home/epics/support/tomoscan/docs/source/tomoScan_13BM.template.rst: WARNING: document isn't included in any toctree
/home/epics/support/tomoscan/docs/source/tomoScan_13BM_settings.req.rst: WARNING: document isn't included in any toctree
/home/epics/support/tomoscan/docs/source/tomoScan_settings.req.rst: WARNING: document isn't included in any toctree
```
Maybe you can figure out why the hidden attribute is no longer working?

**Comment by MarkRivers** [comment] 2020-05-06 15:34
I fixed the problem with the hidden toctree.  I needed to add this entry to html_theme_options{} in conf.py:
```
'includehidden': False
```

I have updated conf.py to add that and re-enabled the toctree:: :hidden: in tomoScanApp.rst. 

Now the warnings are gone and the TOC is no longer visible.

**Comment by decarlof** [comment] 2020-05-06 15:44
@MarkRivers I was looking at the same an tried the 

`exclude_patterns = ['tomoScan_*.*']`

but there are other not so good implications ...

**Comment by decarlof** [comment] 2020-05-06 16:39
@MarkRivers [actually the latest](https://tomoscan.readthedocs.io/en/latest/source/tomoScanApp.html#) built shows the tomoScan* under the tomoScanApp EPICS application menu. Perhaps the `'includehidden': False` did not work?

Let me look more into it

**Comment by decarlof** [comment] 2020-05-06 17:01
@MarkRivers So the issue is only on the readthedoc build. Local build is fine. I will push the changes to fix #46 and keep looking. Probably is a configuration under readthedocs

**Comment by MarkRivers** [comment] 2020-05-06 17:07
I see the same thing, local build it fine but on readthedocs it is acting like it is ignoring the includehidden.  Maybe a different version of Sphinx?

**Comment by MarkRivers** [comment] 2020-05-06 17:30
This is still true after your merge of #47. 

I have changed conf.py to require Sphinx 3.0.3 to see if that fixes the problem.

I pushed and it is building now.

**Comment by MarkRivers** [comment] 2020-05-06 18:00
The build failed on readthedocs, but it builds locally.
```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tomoscan/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tomoscan/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 215, in __init__
    'be built with this version.') % self.config.needs_sphinx)
sphinx.errors.VersionRequirementError: This project needs at least Sphinx v3.0.3 and therefore cannot be built with this version.

Sphinx version error:
This project needs at least Sphinx v3.0.3 and therefore cannot be built with this version.
```
How to we tell readthedocs to use Sphinx 3.0.3?  Do we need a .readthedocs.yml file to tell it load the latest Sphinx.  I am not sure this is even possible, this page
https://docs.readthedocs.io/en/stable/faq.html#my-project-requires-different-settings-than-those-available-under-admin
says you need to send an e-mail to readthedocs.org to change it?

**Comment by MarkRivers** [comment] 2020-05-06 18:05
For now I have commented out needs_sphinx 3.0.3 in conf.py and made the hidden toc_tree into a comment. This will produce warnings on local builds, but it won't show the toctree on readthedocs.

**Comment by decarlof** [comment] 2020-05-06 18:21
OK

> This is still true after your merge of #47.
> 
> I have changed conf.py to require Sphinx 3.0.3 to see if that fixes the problem.
> 
> I pushed and it is building now.

correct merge #47 was just to move the conf.py in the new default location. Old issue should stay the same.

**Comment by decarlof** [comment] 2020-05-06 18:25
> For now I have commented out needs_sphinx 3.0.3 in conf.py and made the hidden toc_tree into a comment. This will produce warnings on local builds, but it won't show the toctree on readthedocs.

OK I think we can close this, the local warning will be a good reminder that needs to be fixed

**Closed as completed by decarlof** 2020-05-06 18:25 UTC
